# Generated by Django 4.1.2 on 2022-12-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_photos_location_remove_photos_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_photos',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
