# Generated by Django 4.1.2 on 2022-12-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_news_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_photos',
            field=models.URLField(blank=True, null=True),
        ),
    ]
