# Generated by Django 4.1.2 on 2022-12-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_news_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
