# Generated by Django 4.1.2 on 2022-12-12 20:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_news_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='photo',
        ),
        migrations.AlterField(
            model_name='news',
            name='news_photos',
            field=cloudinary.models.CloudinaryField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
