# Generated by Django 4.1.2 on 2022-12-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_news_news_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsphotos',
            name='image',
            field=models.ImageField(default=1, upload_to='news/'),
            preserve_default=False,
        ),
    ]
