# Generated by Django 4.1.2 on 2022-12-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_newsphotos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='NewsPhotos',
        ),
    ]
