# Generated by Django 4.1.2 on 2022-12-13 06:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_news_news_photos_delete_newsphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_photos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
