# Generated by Django 4.1.2 on 2022-12-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='acknowledged_by_user',
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instruction_text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
